[DIR-705] Add submit button to time refine component
direktiv/direktiv-ui pull request #437
Opened 2023-08-04 13:26 UTC by sebxian

### Changes
* Uses InputWithButton to add a submit button to the time input in the instance filters
* Fixes a serious bug I noticed by chance: The guard I had previously added to check that time values are not undefined also prevented them having a value of "0".

2023-08-05 07:18 UTC, stefan-kracht requested changes
I like this. Looks so much better with a button!

For me, the time input needs to be a tiny bit bigger now (might be a mac thing?).

![CleanShot 2023-08-05 at 09 13 11@2x](https://github.com/direktiv/direktiv-ui/assets/121789579/8c913d86-e227-4e12-a3b0-2d321c7a01bf)

I also wonder if we might use a different icon? My first impression of that checkmark was, that it looks like it passed a validation and not submit something (like e.g. the username you entered is available). [Maybe this](https://lucide.dev/icons/arrow-right)?

2023-08-07 12:19 UTC, sebxian commented
@stefan-kracht, thanks for the feedback. I updated the submit button icon to ArrowRight, as suggested (17671d312335b4008a794bae571b6fbc6de4bb34)

Regarding the width of the time input, I am not sure what's the best approach. There is no explicit width set on the element. The input uses `w-full` and the parent (Command component) uses `w-min`. Maybe changing it to (or adding) `min-w-min` would solve the issue? Since I cannot see the issue under Linux, I can't try out possible fixes. Could you maybe investigate a fix that works on your Mac?

2023-08-07 13:20 UTC, stefan-kracht commented
> @stefan-kracht, thanks for the feedback. I updated the submit button icon to ArrowRight, as suggested ([17671d3](https://github.com/direktiv/direktiv-ui/commit/17671d312335b4008a794bae571b6fbc6de4bb34))
> 
> Regarding the width of the time input, I am not sure what's the best approach. There is no explicit width set on the element. The input uses `w-full` and the parent (Command component) uses `w-min`. Maybe changing it to (or adding) `min-w-min` would solve the issue? Since I cannot see the issue under Linux, I can't try out possible fixes. Could you maybe investigate a fix that works on your Mac?

I merged the base branch into this branch and had to fix one tiny issue, that broke the layout. And I deleted an old proof of concept component that was not in used as well.

I can reproduce the time input issue outside our app. So it's a Mac/Chrome/Retina related bug. Let's just ignore that for now.

<img width="1470" alt="CleanShot 2023-08-07 at 15 15 38@2x" src="https://github.com/direktiv/direktiv-ui/assets/121789579/6c5b17ae-8ea5-4d92-929e-53644e51a2ef">

Feel free to merge 🚀

2023-08-07 13:20 UTC, stefan-kracht approved these changes

2023-08-07 13:43 UTC, merged