[DIR-197] new services page
direktiv/direktiv-ui pull request #446
Opened 2023-08-14 09:12 UTC by stefan-kracht

2023-08-29 09:42 UTC, sebxian requested changes
The services page and sub pages look good and seem to work as they should.

I must admit, however, that with my limited knowledge and limited time I can invest right now this is only a somewhat superficial impression. It would be very important to have an expert look at this as soon as possible and test it more thoroughly (after merging?).

I have made some suggestions in the code, mostly regarding spelling/readability.

2023-08-30 07:59 UTC, stefan-kracht commented on src/api/services/__tests__/schema.test.ts
> +    test("can not end with various characters that are not lowercase characters or a digit", () => {
I added 1 😊  6440dd7ae57d403b8cec9a6c337e450031503f31

2023-08-30 08:13 UTC, stefan-kracht commented on src/api/services/query/getAll.ts
> +    // reverse the order of functions (newer first)
Yes, this is still an issue I wrote a [ticket](https://linear.app/direktiv/issue/DIR-784/change-order-of-services) and mentioned it in the comment (0f2341e49d4234567bc751c132e863b3ae7416f8)

2023-08-30 08:33 UTC, stefan-kracht commented on src/pages/namespace/Services/Detail/Create.tsx
> +          message: t("pages.services.revision.create.noChanges"),
I like that idea, we should definitely introduce that

2023-08-30 08:41 UTC, stefan-kracht commented on src/pages/namespace/Services/Detail/Create.tsx
> +         * user create one
Yes, we could phrase it like that (1b3a96473fad988b4d52eb873f4c03f46fb108ee)

2023-08-30 08:53 UTC, stefan-kracht commented on src/pages/namespace/Explorer/Tree/NoResult.tsx
> +        button={
Very good idea (3854b37f513d2969f745c448c09ca60770d458f3)!

2023-08-30 08:55 UTC, stefan-kracht commented on src/componentsNext/FormErrors/index.tsx
> +          <li key={key}>{`${key && `${key} :`} ${
Yes, that's a very good catch! (035e178ea2e8aff014e67bfd68b2e02d0ef772cc)

2023-08-30 09:26 UTC, stefan-kracht commented on src/api/services/schema/revisions.ts
> +  // handle status: False with reason: NoTraffic as status: True
Yes, this was not very well explained, I hope this is better: 566804dbb7f98f9a77660191c4104fefdc8182a9

2023-08-30 10:46 UTC, stefan-kracht commented on src/api/services/query/getDetails.ts
> +         * acts like an id)
fixed in d0fa1742611e6a9894d39d4128ccf3cc034ace02

2023-08-30 11:08 UTC, stefan-kracht commented
Thanks for your review @sebxian. I somehow have to reduce the need of language cop in the future :D

- [one minor unresolved issue, that you could check](https://github.com/direktiv/direktiv-ui/pull/446/files/4f7dfd9792ca010e47d6a9b7ca2c3a3083fd46bd#r1307692524) 
- I also 
  - merged the base branch back in and fixed a merge conflict
  - updated an unrelated test according to your language suggestions (6afe1f7e6cd3768b79a58dfbe0d0970166c5c58e)

2023-08-30 14:24 UTC, sebxian approved these changes
Thanks for the updates, @stefan-kracht, they all look good to me!

2023-08-30 14:34 UTC, merged